# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vario <- function(y, w_mat, p) {
    .Call('_MultivCalibration_vario', PACKAGE = 'MultivCalibration', y, w_mat, p)
}

